### ISSUE TITLE
request: keystrokes for "Don't save"

### ISSUE THREAD

**Issue by timvets** [JohannesTaelman/axoloti#56] opened 2015-06-29 13:07 UTC
The dialog "Axoloti asks: Do you want to save changes to..." can now only be closed by clicking.
It would be nice if the keystrokes "tab tab enter" would do the same as clicking on "Don't save" and "tab enter" == clicking on "Save".

**Comment by JohannesTaelman** [comment] 2015-06-29 13:11
This works in Windows. If it does not on linux, the issue is in java/linux.

**Comment by TheTechnobear** [comment] 2015-06-29 13:17
perhaps a linux issue... 
n mac OS X - tab correctly cycles thru button, and space (correctly) activates the chosen option.
enter selects the default option (cancel)
and escape selects cancel.
this all confirms to UI standards.

Id say the only thing that is 'odd' is ENTER should be SAVE, i.e. save is the default.
(agreed?) 

@timvets can you test on linux that tab is not working at all? perhaps window manager setup?

**Comment by timvets** [comment] 2015-06-29 13:24
Yes tab is working, and ...:
It _does_ work with SPACE !
usually ENTER is what I use..., and I still think ENTER would be more intuitive.
but I can live with SPACE :)

**Comment by TheTechnobear** [comment] 2015-06-29 13:28
nah, UI standards dictate ENTER = default option.  
hence the 'debate' about what the default option should be :) 
I checked with other apps, and does appear save=enter, escape = cancel  
... and do not save, is tab, we could change the order so that cancel is next to save, so its "do not save" is tab then space.

**Comment by JohannesTaelman** [comment] 2015-06-29 13:34
Enter/space works on windows too. 
I believe this issue is so tiny that I close it.

**Closed by JohannesTaelman** 2015-06-29 13:34 UTC
